"""upstream 包：SOLO 上游协议适配层。

对应原版 internal/upstream/。
"""

from .constants import (
    ACTIVE_FUNCTION,
    AgentHost,
    AppID,
    ClientID,
    ConsoleHost,
    DeviceBrand,
    EpChat,
    EpCheckinClaim,
    EpCheckinStatus,
    EpEntUsage,
    EpExchange,
    EpModels,
    EpUserInfo,
    Function,
    FunctionDesignLite,
    FunctionDesignRemote,
    FunctionWorkLite,
    FunctionWorkRemote,
    IdeVersion,
    IdeVersionCode,
    OAuthHost,
    OSVersion,
    UgHost,
    active_function,
    function_options,
    is_known_function,
    known_functions,
    set_function,
)

__all__ = [
    "ACTIVE_FUNCTION",
    "AgentHost",
    "AppID",
    "ClientID",
    "ConsoleHost",
    "DeviceBrand",
    "EpChat",
    "EpCheckinClaim",
    "EpCheckinStatus",
    "EpEntUsage",
    "EpExchange",
    "EpModels",
    "EpUserInfo",
    "Function",
    "FunctionDesignLite",
    "FunctionDesignRemote",
    "FunctionWorkLite",
    "FunctionWorkRemote",
    "IdeVersion",
    "IdeVersionCode",
    "OAuthHost",
    "OSVersion",
    "UgHost",
    "active_function",
    "function_options",
    "is_known_function",
    "known_functions",
    "set_function",
]
